### ISSUE TITLE
Seems to be broken in 0.12.0

### ISSUE THREAD

**Issue by DaneEveritt** [jandre/node-userid#2]
Hi there,

This seems to no longer work on NodeJS 0.12.0. The following errors are spewed when trying to install.

```
npm WARN package.json trim@0.0.1 No repository field.
npm WARN package.json userid@0.1.1 No repository field.
|
> userid@0.1.1 install /Users/DaneEveritt/Sites/gsd/node_modules/userid
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/userid/src/userid.o
../src/userid.cc:25:25: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> Uid(const Arguments& args);
                        ^~~~~~~~~
                        v8::internal::Arguments
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/userid.cc:26:30: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> UserName(const Arguments& args);
                             ^~~~~~~~~
                             v8::internal::Arguments
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/userid.cc:27:31: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> GroupName(const Arguments& args);
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/userid.cc:28:25: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> Gid(const Arguments& args);
                        ^~~~~~~~~
                        v8::internal::Arguments
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/userid.cc:32:15: error: calling a protected constructor of class
      'v8::HandleScope'
  HandleScope scope;
              ^
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../src/userid.cc:33:23: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(String::NewSymbol("uid"), FunctionTemplate::New(Uid)->GetF...
              ~~~~~~~~^
../src/userid.cc:34:23: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(String::NewSymbol("username"), FunctionTemplate::New(UserN...
              ~~~~~~~~^
../src/userid.cc:35:23: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(String::NewSymbol("gid"), FunctionTemplate::New(Gid)->GetF...
              ~~~~~~~~^
../src/userid.cc:36:23: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(String::NewSymbol("groupname"), FunctionTemplate::New(Grou...
              ~~~~~~~~^
../src/userid.cc:39:31: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> GroupName(const Arguments& args)
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/userid.cc:41:15: error: calling a protected constructor of class
      'v8::HandleScope'
  HandleScope scope;
              ^
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../src/userid.cc:44:11: error: member access into incomplete type 'const
      v8::internal::Arguments'
  if (args.Length() > 0 && args[0]->IsInt32()) {
          ^
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward
      declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/userid.cc:45:26: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
    group = getgrgid(args[0]->Int32Value());
                     ~~~~^~
../src/userid.cc:47:52: error: no member named 'New' in 'v8::String'
    return ThrowException(Exception::Error(String::New("you must supply ...
                                           ~~~~~~~~^
../src/userid.cc:51:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(String::New(group->gr_name));
           ~~~~~ ^
../src/userid.cc:51:32: error: no member named 'New' in 'v8::String'
    return scope.Close(String::New(group->gr_name));
                       ~~~~~~~~^
../src/userid.cc:53:52: error: no member named 'New' in 'v8::String'
    return ThrowException(Exception::Error(String::New("gid not found")));
                                           ~~~~~~~~^
../src/userid.cc:57:25: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> Gid(const Arguments& args)
                        ^~~~~~~~~
                        v8::internal::Arguments
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/userid.cc:59:15: error: calling a protected constructor of class
      'v8::HandleScope'
  HandleScope scope;
              ^
/Users/DaneEveritt/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/userid/src/userid.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/DaneEveritt/Sites/gsd/node_modules/userid
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "userid"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! userid@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the userid@0.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the userid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls userid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/DaneEveritt/Sites/gsd/npm-debug.log
```

**Comment by jandre** [comment]
Yeah I haven't made it compatible with the 'new' way to do c++ modules yet :(

Pull requests accepted? :)

**Comment by DaneEveritt** [comment]
I would do a PR, but alas I don't know C++ :(

**Comment by franck34** [comment]
any update on this ? thanks

**Comment by jandre** [comment]
Should be addressed in 0.1.2, thanks!
